### ISSUE TITLE
Passing API Key 

### ISSUE THREAD

**Issue by Seedser** [clough42/node-red-contrib-thingspeak42#4]
I would like to use one function to send to multiple Thingspeak channels.  
My function identifies unique variable, then assigns a known API Key. 
---
var Node = JSON.parse(msg.payload);
var api_key
if (Node == 100) {
 var api_key = "xxxxxxxx1";
 }
if (Node == 200) {
 api_key = "xxxxxxxx2";
}
msg.payload = api_key;
return msg;

**Comment by sushicodeur** [comment]
You can probably use a switch block before calling multiple thingspeak42 blocks (one for each output of the switch block), each one configured with its api key.

**Comment by clough42** [comment]
Agreed.  A switch block is the right way to do this.  The API keys should be kept in secure storage and should probably not be sent around in messages.
