### ISSUE TITLE
Multiple values arrive: which get sent?

### ISSUE THREAD

**Issue by jwosnick** [clough42/node-red-contrib-thingspeak42#6]
This is a very useful node, thanks for creating it. It's not clear to me how the node handles an event where multiple messages from the same topic arrive during the time-out period.

For example, if there is a 60-second time-out period and four different messages arrive on the topic foo/bar, which gets sent to Thingspeak? The most recent, or an average, or the peak value? Is there a way to control this?

**Comment by clough42** [comment]
The most recent value for each topic is sent.

Only one value is stored per topic.  If another value comes in before the values are uploaded, it replaces the previous value.  When data is uploaded to ThingSpeak, all stored values are cleared.

I use this with sensors that publish multiple values on different topics.  My weather station sends a burst of values for temperature, humidity, etc. and I use this node to combine them and upload to ThingSpeak together.  In my case, the weather station reports every five minutes, but I only upload to ThingSpeak every 30 minutes.  The last published value for each topic gets sent.
